# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='section',
            field=models.CharField(max_length=5, null='21231'),
        ),
        migrations.AddField(
            model_name='mail',
            name='termcode',
            field=models.CharField(default='172s', max_length=4),
        ),
    ]
