# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mail2', '0002_auto_20171117_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='section',
            field=models.CharField(default=11111, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='termcode',
            field=models.CharField(max_length=4),
        ),
    ]
