# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mail2', '0002_auto_20180531_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mail2.Mail'),
        ),
    ]
