# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail2', '0003_auto_20171117_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='fk_to',
        ),
        migrations.AddField(
            model_name='route',
            name='to',
            field=models.CharField(default='', max_length=300),
        ),
    ]
