# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail2', '0004_auto_20180112_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='fk_mail',
        ),
        migrations.AddField(
            model_name='attachment',
            name='hashedname',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='m2m_mail',
            field=models.ManyToManyField(to='Mail2.Mail'),
        ),
    ]
